[workspace]
members = [ "borrow-stack-ex", "name-shuffle","number-puzzle", "super-mod-pow"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tinyvec = "1.6.0"
num-traits = "0.2.19"
rand = "0.8.5"
proconio = "0.4.5"
