[package]
name = "number-puzzle"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyvec.workspace = true
num-traits.workspace = true
